kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclass-jenkins
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
  shareName: jenkins

#Aqui criamos o StorageClass que é necessário para a criação do pvc, nele definimos algumas regras relacionadas aos arquivos e seu sku